version: '3.8'
services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: testkeyid
      MINIO_SECRET_KEY: secretaccesskey
    command: server /data

